import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#93000a",
        "surface-dim": "#091326",
        "on-secondary-container": "#00566a",
        secondary: "#a5e7ff",
        "inverse-surface": "#d9e2fd",
        "primary-fixed": "#d8e2ff",
        "on-surface": "#d9e2fd",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#050e21",
        "secondary-container": "#00d2ff",
        "on-primary-fixed-variant": "#004397",
        "on-background": "#d9e2fd",
        "on-secondary-fixed": "#001f28",
        "on-tertiary-container": "#ffffff",
        "inverse-primary": "#0059c5",
        "on-error": "#690005",
        "surface-container-high": "#212a3e",
        "secondary-fixed-dim": "#47d6ff",
        "on-secondary": "#003543",
        "surface-bright": "#30394e",
        "on-surface-variant": "#c1c6d7",
        "on-tertiary": "#002b74",
        primary: "#aec6ff",
        "tertiary-fixed": "#dae2ff",
        background: "#091326",
        "surface-container-low": "#121b2f",
        "outline-variant": "#414754",
        surface: "#091326",
        "primary-fixed-dim": "#aec6ff",
        "surface-container": "#161f33",
        "surface-container-highest": "#2c3549",
        "on-tertiary-fixed-variant": "#003fa3",
        "surface-variant": "#2c3549",
        "on-primary-fixed": "#001a43",
        "tertiary-container": "#386fea",
        "inverse-on-surface": "#273045",
        error: "#ffb4ab",
        "primary-container": "#0070f3",
        "on-secondary-fixed-variant": "#004e60",
        "tertiary-fixed-dim": "#b2c5ff",
        "secondary-fixed": "#b6ebff",
        tertiary: "#b2c5ff",
        outline: "#8b90a0",
        "surface-tint": "#aec6ff",
        "on-primary-container": "#ffffff",
        "on-primary": "#002e6b",
        "on-tertiary-fixed": "#001849",
      },
      spacing: {
        "space-lg": "1.5rem",
        "gutter-mobile": "1rem",
        "space-xl": "2rem",
        "gutter-desktop": "1.5rem",
        "margin-desktop": "2.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "margin-mobile": "1.25rem",
        "space-2xs": "0.25rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "space-xs": "0.5rem",
      },
      fontFamily: {
        sans: ["var(--font-jakarta)", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "600" }],
        "headline-xl": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
